language: ruby
cache: bundler
gemfile: Gemfile
install: bundle install
rvm:
  - 2.5
scala: 2.11.2
jdk:
  - openjdk8
script:
  # - bundle exec jekyll algolia --source docs --destination docs/_site --config docs/_config.yml
  - JEKYLL_ENV=production bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check_html --allow_hash_href --alt_ignore '/.*/' --only_4xx --disable_external
after_success: s3_website push
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
